### ISSUE TITLE
Problem in sdcTable::protectLinkedTables

### ISSUE THREAD

**Issue by olangsrud** [sdcTools/UserSupport#133]
*Please specify*  
**SDC tool used:** sdcTable
**Version used:**  0.30 
**Operating system used:**  Windows

---

I intended to make a small example that demonstrates that suppressing linked tables by iteration is not safe (see https://github.com/olangsrud/experimentalRpackage/blob/master/R/PTxyz.R ). But the small dataset I looked at discovered another problem in protectLinkedTables. See the code below.

```
library(sdcTable)

# Data including two aggregating variables.
z <- data.frame(region = c("A", "B", "I", "J", "K"), 
                county = c("county-1", "county-4", "county-1", "county-10", "county-10"), 
                group = c("BIG", "BIG", "small", "small", "small"), 
                n = c(11, 7, 3, 9, 4), stringsAsFactors = FALSE)

# Defining hierarchies ( can be done by SSBtools::FindDimLists(z[, 1:3]))
dimList1 <- list(region = data.frame(levels = c("@", "@@", "@@@", "@@@", "@@", "@@@", "@@@", "@@", "@@@"), 
                                     codes = c("Total", "county-1", "A", "I", "county-10", "J", "K", "county-4", "B"), 
                                     stringsAsFactors = FALSE))
dimList2 <- list(region = data.frame(levels = c("@", "@@", "@@@", "@@@", "@@", "@@@", "@@@", "@@@"), 
                                     codes = c("Total", "BIG", "A", "B", "small", "I", "J", "K"), 
                                     stringsAsFactors = FALSE))
# Defining common cells
commonCells <- list(region = list("region", c("Total", "A", "B", "I", "J", "K"))[c(1, 1, 2, 2)])


# makeProblem and primarySuppression in sdcTable 
problem1 <- makeProblem(z, dimList1, dimVarInd = 1, freqVarInd = 4)
problem2 <- makeProblem(z, dimList2, dimVarInd = 1, freqVarInd = 4)
primary1 <- primarySuppression(problem1, type = "freq", maxN = 3)
primary2 <- primarySuppression(problem2, type = "freq", maxN = 3)

# Secondary suppression of linked tables 
protected <- protectLinkedTables(primary1, primary2, commonCells, method = "SIMPLEHEURISTIC", verbose = TRUE)

# Look at output
getInfo(protected[[1]], type = "finalData")
getInfo(protected[[2]], type = "finalData")


# In the last table region B is safe. Thus, region A (suppressed) can be computed from BIG. 
# If method is changed to HITAS, region B is safe in the first table, but not in the second table.

```

**Comment by bernhard-da** [comment]
hi @olangsrud thx for spotting this issue. i have pushed a fix in https://github.com/sdcTools/sdcTable/commit/b5665aafa4f9317e28df94c0a425c58851779d19 and would be happy if you could check if it indeed solves the problem. thx!

**Comment by olangsrud** [comment]
Sorry, I got: 

```
csp.cpp:2:18: fatal error: glpk.h: No such file or directory
 #include <glpk.h>
                  ^
compilation terminated.
make: *** [C:/PROGRA~1/R/R-36~1.1/etc/i386/Makeconf:215: csp.o] Error 1
ERROR: compilation failed for package 'sdcTable'
* removing 'C:/Program Files/R/R-3.6.1/library/sdcTable'
Error: Failed to install 'sdcTable' from GitHub:
```

**Comment by bernhard-da** [comment]
hi @olangsrud  yes, you need the glpk-header files (winglpk.sourceforge.net) installed. tomorrow, i can link you a windows-test binary via win-builder (I sent the file to build but have not yet gotten the result back)

**Comment by bernhard-da** [comment]
@olangsrud win-builder took really long this time. [**here**](https://cloud.bmeindl.eu/f/fc7fee03e1044d67b46e/?dl=1) you can find a test-version built for windows.

**Comment by olangsrud** [comment]
Tank you for the zip-file.

The problem is, unfortunately, not solved.  Last time I wrote:  _“In the last table region B is safe. Thus, region A (suppressed) can be computed from BIG.”_  In that case, the suppression was consistent, so B was also safe in the first table ("SIMPLEHEURISTIC"). This time (new zip-file), B is safe in the last table, but not in the first table. The suppression pattern is not consistent.

Also note that “unwanted printing to screen” appears in the new version.

Original output 

```
> # Look at output
> getInfo(protected[[1]], type = "finalData")
      region Freq sdcStatus
1:     Total   34         s
2:  county-1   14         s
3:         A   11         x
4:         I    3         u
5: county-10   13         s
6:         J    9         s
7:         K    4         u
8:  county-4    7         s
9:         B    7         s
> getInfo(protected[[2]], type = "finalData")
   region Freq sdcStatus
1:  Total   34         s
2:    BIG   18         s
3:      A   11         u
4:      B    7         s
5:  small   16         s
6:      I    3         u
7:      J    9         s
8:      K    4         x
```

New output

```
> # Look at output
> getInfo(protected[[1]], type = "finalData")
      region Freq sdcStatus
1:     Total   34         s
2:  county-1   14         s
3:         A   11         x
4:         I    3         u
5: county-10   13         s
6:         J    9         x
7:         K    4         u
8:  county-4    7         s
9:         B    7         s
> getInfo(protected[[2]], type = "finalData")
   region Freq sdcStatus
1:  Total   34         s
2:    BIG   18         s
3:      A   11         u
4:      B    7         x
5:  small   16         s
6:      I    3         u
7:      J    9         u
8:      K    4         x
> 
```

**Comment by bernhard-da** [comment]
@olangsrud i think the "issue" is because of how the hierarchies/common cells are specified. in table 1 you specified `B` being a `"bogus"` code to `county-4`. in `commonCells` however, it is stated that codes `B` must exist in both tables. While this is true, the following problem arises. Internally, I remove all `bogus` codes from the hierarchies prior to anonymizing and afterwards, these duplicated cells are re-added. In you example, rows with region == `"B"` are removed from the first table. Then, however, the `B` from the second table has no matching partner and it is not checked, if `"county-4"` (first table) and `"B"` (second table) have the same anonymization state. 

you can check that you get the expected result when you specifiy ``commonCells` differently

````
commonCells <- list(region=list(
    "region", "region", 
    c("Total", "A", "county-4", "I", "J", "K"),
    c("Total", "A", "B", "I", "J", "K")
  ))
````
I am not sure however what I will do about this. Perhaps an error if not all common-codes are available at runtime or more rigid checking of the `commonCells` input ...

ps: i can't reproduce the "unwanted printing to screen". did you set `verbose = FALSE`?

**Comment by olangsrud** [comment]
Yes, I used the same code with verbose = TRUE. I forgot that when I commented.

**Comment by olangsrud** [comment]
Yes, I see that the new version +  new definition of common cells solves the problem.

In case of duplicated codes, are you always removing the code with most @’s?

**Comment by bernhard-da** [comment]
> Yes, I see that the new version + new definition of common cells solves the problem.
great !

> In case of duplicated codes, are you always removing the code with most @’s?
yes, that's what is done ...

**Comment by olangsrud** [comment]
Thanks. Then I will solve the problem by specifying the common cells differently. 
I will make use of the function DimListReCode as specified below.

```
DimListReCode <- function(codes, dimList) {
  hi <- SSBtools::DimList2Hierarchy(dimList)
  dupCodes <- unique(hi$mapsTo[duplicated(hi$mapsTo)])
  hi <- hi[!(hi$mapsTo %in% dupCodes), ]
  if (nrow(hi) == 0) 
    return(codes)
  for (i in 0:nrow(hi)) {
    ma <- match(codes, hi$mapsFrom)
    isMatch <- !is.na(ma)
    if (!any(isMatch)) 
      return(codes)
    codes[isMatch] <- hi$mapsTo[ma[isMatch]]
  }
  stop("Something is wrong. Cyclic hierarchy?")
}
```

Examples using dimList1 and dimList2 as specified above.

```
DimListReCode(c("A", "B", "I"), dimList1$region)
DimListReCode(c("A", "B", "I"), dimList2$region)
list3 <- rbind(dimList1$region, c("@@", "a"), c("@@@", "b"), c("@@@@", "c"), c("@@@@@", "d"))
DimListReCode(c("d", "A", "B", "I"), list3)
DimListReCode(c("a", "b", "c", "d", "A", "B", "I"), list3)
```
